### Create User (POST)
POST http://localhost:8080/order
Content-Type: application/json

{
  "memo": "Sample no memo"
}

### Get All orders (GET)
GET http://localhost:8080/order

### Pay order (POST)
POST http://localhost:8080/order/1/pay

### Ship order (POST)
POST http://localhost:8080/order/1/ship

### Cancel order (POST)
POST http://localhost:8080/order/1/cancel

