### Create User (POST)
POST http://localhost:8080/order
Content-Type: application/json

{
  "memo": "Sample no memo"
}

### Get All orders (GET)
GET http://localhost:8080/order

### Pay order (PUT)
POST http://localhost:8080/order/1/pay
# Content-Type: application/json

### Ship order (PUT)
POST http://localhost:8080/order/1/ship
# Content-Type: application/json

